#!/bin/bash

# 定义目录和日期
posts_dir="_posts"
date=$(date +%Y-%m-%d)

# 检查参数
if [ -z "$1" ]; then
  read -rp "😁 请输入文章标题：" input_title
  if [ -z "$input_title" ]; then
    echo "❌ 错误：文章标题不能为空"
    exit 1
  fi
  set -- "$input_title"
fi

# 处理标题（空格转连字符，转小写）
title=$(echo "$1" | tr ' ' '-' | tr '[:upper:]' '[:lower:]')
filename="$date-$title.md"

# 创建目录（如果不存在）
mkdir -p "$posts_dir"

# 生成文件内容
# echo "---
# title: \"$1\"
# date: $date
# ---
# " > "$posts_dir/$filename"

echo "# $1
" > "$posts_dir/$filename"

echo "✅ 文章已创建：$posts_dir/$filename"
code --goto "$posts_dir/$filename:3:0"